### ISSUE TITLE
Update gradle version to latest 

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-sdk-js#194]
The deprecated configuration `compile` is used in the SDK build.gradle, so when the user creates a project with newer gradle version, they will encounter following error. 

```
yarn run v1.22.17
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 955 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
error Failed to launch emulator. Reason: Emulator exited before boot..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :react-native-gradle-plugin:compileKotlin
'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (157, 32): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (163, 31): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (171, 36): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: (100, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with root to point to your root project and reactNativeDir to point to the folder of the react-native NPM package
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (27, 51): 'BaseVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (130, 12): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (131, 12): 'LibraryVariant' is deprecated. Deprecated in Java
w: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (251, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Task :react-native-gradle-plugin:compileJava

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 4 executed, 2 up-to-date
Note: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* Where:
Build file '/.../authgear-demo-app-rn/node_modules/@authgear/react-native/android/build.gradle' line: 86

* What went wrong:
A problem occurred configuring project ':authgear_react-native'.
> Configuration with name 'compile' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /.../authgear-demo-app-rn/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* Where:
Build file '/.../authgear-demo-app-rn/node_modules/@authgear/react-native/android/build.gradle' line: 86

* What went wrong:
A problem occurred configuring project ':authgear_react-native'.
> Configuration with name 'compile' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s

    at makeError (/.../authgear-demo-app-rn/node_modules/execa/index.js:174:9)
    at /.../authgear-demo-app-rn/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/.../authgear-demo-app-rn/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/.../authgear-demo-app-rn/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
```

refs: https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

**Comment by louischan-oursky** [comment]
The implication is our SDK is going to support newer versions of React Native.

**Comment by axolotl0212** [comment]
@louischan-oursky Simply changing all `compile` in `build.gradle` to `implementation` should fix the build error? (As `implementation` is supported in Gradle 3.4.1 ?) I think there is 2 separate issue?

1. Fix build error in React Native app using Authgear SDK and gradle >= 7.0 
2. Upgrade gradle used by Authgear SDK

**Comment by louischan-oursky** [comment]
Thank @axolotl0212 . @andychow326 Please have a try.

**Comment by axolotl0212** [comment]
In Authgear SDK build.gradle, there is a line 

```
classpath += file(project.getConfigurations().getName('compile').asList())
```

I believe this line causes the error. However fixing this is separated from upgrading gradle?
