### ISSUE TITLE
Invalid page is shown when authentication complete in Android

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-sdk-js#240]

**Comment by carmenlau** [comment]
To reproduce the problem, I did more testing on the issue in 2 directions:

1. Changing notification settings during the middle of the authentication flow (reported by QA)
2. Changing orientation during the middle of the authentication flow

I tried both cases on an android phone with Android 11, it works normally.

When I tried both cases on the emulator (API level 33, Android 13):

1. I can repeat what QA mentioned, it shows the invalid screen. The react runtime is dead with the following exception:

```
2023-03-27 14:41:33.287 10842-10842/com.reactnativeexample E/SoLoader: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.reactnativeexample/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~ODfNKFc376pFs-fj3zGTWQ==/com.reactnativeexample-h7cgBRmrDqNV-1_Z11JsSw==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	Native lib dir: /data/app/~~ODfNKFc376pFs-fj3zGTWQ==/com.reactnativeexample-h7cgBRmrDqNV-1_Z11JsSw==/lib/arm64
     result: 0
```

It looks like a react-native problem, and the triggering steps are not common. Maybe we will skip this first.

2. When changing the orientation during the middle of the authentication flow. The app crashed and restarted when the authentication flow is completed. And the error log:

```
2023-03-27 15:03:04.502 14985-14985/com.reactnativeexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.reactnativeexample, PID: 14985
    java.lang.RuntimeException: Unable to resume activity {com.reactnativeexample/com.authgear.reactnative.OAuthCoordinatorActivity}: java.lang.NullPointerException: uriString
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4773)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.NullPointerException: uriString
        at android.net.Uri$StringUri.<init>(Uri.java:504)
        at android.net.Uri$StringUri.<init>(Unknown Source:0)
        at android.net.Uri.parse(Uri.java:466)
        at com.authgear.reactnative.OAuthCoordinatorActivity.startAuthorizationActivity(OAuthCoordinatorActivity.java:59)
        at com.authgear.reactnative.OAuthCoordinatorActivity.onResume(OAuthCoordinatorActivity.java:38)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1564)
        at android.app.Activity.performResume(Activity.java:8437)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4763)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7872) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

I created a PR (https://github.com/authgear/authgear-sdk-js/pull/241) to fix scenario 2.

Todo to me:

- Ensure we don't handle scenario 1 in this stage.
- Perform more testing to ensure the PR solves the changing orientation problem.

**Comment by carmenlau** [comment]
For scenario 2, the steps to reproduce

Testing device: Emulator, Pixel 4 API 33

1. Allow auto-rotate in the device settings
2. Start the reactnative demo app, fill-in endpoint, client id, and start authentication
3. During the authentication, change the device orientation
4. Complete the authentication
5. The app crashed at the end of authentication

**Comment by kiootic** [comment]
Another potential bug is in `OAuthRedirectActivity`, it launches `OAuthCoordinatorActivity` with `createRedirectIntent`, which does not include `KEY_AUTHORIZATION_URL`. If the activity is started from scratch due to this intent, it may lead to problem.

**Comment by carmenlau** [comment]
Thanks @kiootic, let me double check

**Comment by louischan-oursky** [comment]
@fungc-io @tung2744  Released version 2.1.0 which contains this fix.
